import { describe, expect, it } from 'vitest'
import { backgroundColorFixtures } from './fixtures/tailwind-background-color-rewrite'
import { backgroundStyleFixtures } from './fixtures/tailwind-background-style-rewrite'
import { borderWidthFixtures, roundedFixtures } from './fixtures/tailwind-border-rewrite'
import { leadingFixtures } from './fixtures/tailwind-leading-rewrite'
import { outlineFixtures } from './fixtures/tailwind-outline-rewrite'
import { ringFixtures } from './fixtures/tailwind-ring-rewrite'
import { borderSpacingSpaceFixtures } from './fixtures/tailwind-spacing-border-spacing-space-rewrite'
import { gapInsetScrollFixtures } from './fixtures/tailwind-spacing-gap-inset-scroll-rewrite'
import { paddingMarginFixtures } from './fixtures/tailwind-spacing-padding-margin-rewrite'
import { strokeFixtures } from './fixtures/tailwind-stroke-rewrite'
import { trackingFixtures } from './fixtures/tailwind-tracking-rewrite'
import { transitionFixtures } from './fixtures/tailwind-transition-rewrite'
import { textFixtures } from './fixtures/tailwind-text-rewrite'
import { tailwindUtilitySpecs } from './tailwind-utility-spec'

function getSpec(id: string) {
  return tailwindUtilitySpecs.find(spec => spec.id === id)
}

describe('tailwind utility spec', () => {
  it('tracks unique utility ids', () => {
    const ids = tailwindUtilitySpecs.map(spec => spec.id)
    expect(new Set(ids).size).toBe(ids.length)
  })

  it('keeps the border rewrite template in sync with the shared fixtures', () => {
    const backgroundColorSpec = getSpec('background-color')
    const backgroundStyleSpec = getSpec('background-style')
    const borderWidthSpec = getSpec('border-width')
    const borderRadiusSpec = getSpec('border-radius')
    const borderSpacingSpaceSpec = getSpec('border-spacing-space')
    const leadingSpec = getSpec('leading')
    const gapInsetScrollSpec = getSpec('gap-inset-scroll')
    const outlineSpec = getSpec('outline')
    const paddingMarginSpec = getSpec('padding-margin')
    const ringSpec = getSpec('ring')
    const strokeSpec = getSpec('stroke')
    const trackingSpec = getSpec('tracking')
    const transitionSpec = getSpec('transition')
    const textSpec = getSpec('text')

    expect(backgroundColorSpec).toBeTruthy()
    expect(backgroundStyleSpec).toBeTruthy()
    expect(borderWidthSpec).toBeTruthy()
    expect(borderRadiusSpec).toBeTruthy()
    expect(borderSpacingSpaceSpec).toBeTruthy()
    expect(leadingSpec).toBeTruthy()
    expect(gapInsetScrollSpec).toBeTruthy()
    expect(outlineSpec).toBeTruthy()
    expect(paddingMarginSpec).toBeTruthy()
    expect(ringSpec).toBeTruthy()
    expect(strokeSpec).toBeTruthy()
    expect(trackingSpec).toBeTruthy()
    expect(transitionSpec).toBeTruthy()
    expect(textSpec).toBeTruthy()

    expect(backgroundColorSpec?.canonical).toEqual([...backgroundColorFixtures.canonical])
    expect(backgroundColorSpec?.invalid).toEqual([...backgroundColorFixtures.invalid])
    expect(backgroundColorSpec?.sourceFiles).toEqual(['src/_rules/color.ts'])
    expect(backgroundColorSpec?.category).toBe('color')
    expect(backgroundColorSpec?.supportsPrefix).toBe(true)
    expect(backgroundColorSpec?.supportsVariants).toBe(true)
    expect(backgroundColorSpec?.invalid).toContain('bg-#fff')
    expect(backgroundColorSpec?.invalid).toContain('bg-op50')
    expect(backgroundStyleSpec?.canonical).toEqual([...backgroundStyleFixtures.canonical])
    expect(backgroundStyleSpec?.invalid).toEqual([...backgroundStyleFixtures.invalid])
    expect(backgroundStyleSpec?.sourceFiles).toEqual(['src/_rules-wind3/background.ts'])
    expect(backgroundStyleSpec?.category).toBe('layout')
    expect(backgroundStyleSpec?.supportsPrefix).toBe(true)
    expect(backgroundStyleSpec?.supportsVariants).toBe(true)
    expect(backgroundStyleSpec?.invalid).toContain('bg-gradient-linear')
    expect(backgroundStyleSpec?.invalid).toContain('shape-r')
    expect(ringSpec?.canonical).toEqual([...ringFixtures.canonical])
    expect(ringSpec?.invalid).toEqual([...ringFixtures.invalid])
    expect(ringSpec?.sourceFiles).toEqual(['src/_rules/ring.ts'])
    expect(ringSpec?.category).toBe('behavior')
    expect(ringSpec?.supportsPrefix).toBe(true)
    expect(ringSpec?.supportsVariants).toBe(true)
    expect(ringSpec?.invalid).toContain('ring-op50')
    expect(ringSpec?.invalid).toContain('ring-offset-opacity-50')
    expect(borderWidthSpec?.invalid).toContain('border-10px')
    expect(borderRadiusSpec?.invalid).toContain('rounded-lt-lg')
    expect(borderWidthSpec?.supportsPrefix).toBe(true)
    expect(borderWidthSpec?.supportsVariants).toBe(true)
    expect(borderRadiusSpec?.supportsPrefix).toBe(true)
    expect(borderRadiusSpec?.supportsVariants).toBe(true)

    expect(borderWidthSpec?.canonical).toEqual([...borderWidthFixtures.canonical])
    expect(borderWidthSpec?.invalid).toEqual([...borderWidthFixtures.invalid])
    expect(borderRadiusSpec?.canonical).toEqual([...roundedFixtures.canonical])
    expect(borderRadiusSpec?.invalid).toEqual([...roundedFixtures.invalid])
    expect(borderSpacingSpaceSpec?.canonical).toEqual([...borderSpacingSpaceFixtures.canonical])
    expect(borderSpacingSpaceSpec?.invalid).toEqual([...borderSpacingSpaceFixtures.invalid])
    expect(borderSpacingSpaceSpec?.sourceFiles).toEqual(['src/_rules-wind3/table.ts', 'src/_rules-wind3/spacing.ts', 'src/rules.ts'])
    expect(borderSpacingSpaceSpec?.category).toBe('layout')
    expect(borderSpacingSpaceSpec?.supportsPrefix).toBe(true)
    expect(borderSpacingSpaceSpec?.supportsVariants).toBe(true)
    expect(borderSpacingSpaceSpec?.invalid).toContain('borderspacing-2')
    expect(borderSpacingSpaceSpec?.invalid).toContain('space-inline-4')
    expect(leadingSpec?.canonical).toEqual([...leadingFixtures.canonical])
    expect(leadingSpec?.invalid).toEqual([...leadingFixtures.invalid])
    expect(leadingSpec?.sourceFiles).toEqual(['src/_rules/typography.ts'])
    expect(leadingSpec?.category).toBe('typography')
    expect(leadingSpec?.supportsPrefix).toBe(true)
    expect(leadingSpec?.supportsVariants).toBe(true)
    expect(leadingSpec?.invalid).toContain('lh-6')
    expect(leadingSpec?.invalid).toContain('leading-20px')
    expect(gapInsetScrollSpec?.canonical).toEqual([...gapInsetScrollFixtures.canonical])
    expect(gapInsetScrollSpec?.invalid).toEqual([...gapInsetScrollFixtures.invalid])
    expect(gapInsetScrollSpec?.sourceFiles).toEqual(['src/_rules/gap.ts', 'src/_rules/position.ts', 'src/_rules-wind3/scrolls.ts'])
    expect(gapInsetScrollSpec?.category).toBe('layout')
    expect(gapInsetScrollSpec?.supportsPrefix).toBe(true)
    expect(gapInsetScrollSpec?.supportsNegative).toBe(true)
    expect(gapInsetScrollSpec?.supportsVariants).toBe(true)
    expect(gapInsetScrollSpec?.invalid).toContain('gap-row-4')
    expect(gapInsetScrollSpec?.invalid).toContain('scroll-m4')
    expect(paddingMarginSpec?.canonical).toEqual([...paddingMarginFixtures.canonical])
    expect(paddingMarginSpec?.invalid).toEqual([...paddingMarginFixtures.invalid])
    expect(paddingMarginSpec?.sourceFiles).toEqual(['src/_rules/spacing.ts'])
    expect(paddingMarginSpec?.category).toBe('layout')
    expect(paddingMarginSpec?.supportsPrefix).toBe(true)
    expect(paddingMarginSpec?.supportsNegative).toBe(true)
    expect(paddingMarginSpec?.supportsVariants).toBe(true)
    expect(paddingMarginSpec?.invalid).toContain('p4')
    expect(paddingMarginSpec?.invalid).toContain('mx-var(--gap)')
    expect(strokeSpec?.canonical).toEqual([...strokeFixtures.canonical])
    expect(strokeSpec?.invalid).toEqual([...strokeFixtures.invalid])
    expect(strokeSpec?.sourceFiles).toEqual(['src/_rules/svg.ts'])
    expect(strokeSpec?.category).toBe('color')
    expect(strokeSpec?.supportsPrefix).toBe(true)
    expect(strokeSpec?.supportsVariants).toBe(true)
    expect(strokeSpec?.invalid).toContain('stroke-width-2')
    expect(strokeSpec?.invalid).toContain('stroke-size-2')
    expect(trackingSpec?.canonical).toEqual([...trackingFixtures.canonical])
    expect(trackingSpec?.invalid).toEqual([...trackingFixtures.invalid])
    expect(trackingSpec?.sourceFiles).toEqual(['src/_rules/typography.ts'])
    expect(trackingSpec?.category).toBe('typography')
    expect(trackingSpec?.supportsPrefix).toBe(true)
    expect(trackingSpec?.supportsVariants).toBe(true)
    expect(trackingSpec?.invalid).toContain('font-tracking-wide')
    expect(trackingSpec?.invalid).toContain('tracking-0.2em')
    expect(transitionSpec?.canonical).toEqual([...transitionFixtures.canonical])
    expect(transitionSpec?.invalid).toEqual([...transitionFixtures.invalid])
    expect(transitionSpec?.sourceFiles).toEqual(['src/_rules/transition.ts', 'src/_theme/transition.ts'])
    expect(transitionSpec?.category).toBe('behavior')
    expect(transitionSpec?.supportsPrefix).toBe(true)
    expect(transitionSpec?.supportsVariants).toBe(true)
    expect(transitionSpec?.invalid).toContain('property-opacity')
    expect(transitionSpec?.invalid).toContain('transition-ease-linear')

    expect(outlineSpec?.canonical).toEqual([...outlineFixtures.canonical])
    expect(outlineSpec?.invalid).toEqual([...outlineFixtures.invalid])
    expect(outlineSpec?.sourceFiles).toEqual(['src/_rules/behaviors.ts'])
    expect(outlineSpec?.category).toBe('behavior')
    expect(outlineSpec?.supportsPrefix).toBe(true)
    expect(outlineSpec?.supportsVariants).toBe(true)
    expect(textSpec?.canonical).toEqual([...textFixtures.canonical])
    expect(textSpec?.invalid).toEqual([...textFixtures.invalid])
    expect(textSpec?.sourceFiles).toEqual(['src/_rules/typography.ts'])
    expect(textSpec?.category).toBe('typography')
    expect(textSpec?.supportsPrefix).toBe(true)
    expect(textSpec?.supportsVariants).toBe(true)
    expect(textSpec?.invalid).toContain('text-#fff')
    expect(textSpec?.invalid).toContain('text-color-red-500')

    for (const spec of [backgroundColorSpec, backgroundStyleSpec, borderWidthSpec, borderRadiusSpec, borderSpacingSpaceSpec, leadingSpec, gapInsetScrollSpec, outlineSpec, paddingMarginSpec, ringSpec, strokeSpec, trackingSpec, transitionSpec, textSpec].filter(Boolean)) {
      expect(spec?.canonical.length).toBeGreaterThan(0)
      expect(spec?.invalid.length).toBeGreaterThan(0)
      expect(spec?.sourceFiles.length).toBeGreaterThan(0)
    }
  })
})
