import { describe, expect, it } from 'vitest'
import { accentFixtures } from './fixtures/tailwind-accent-rewrite'
import { aspectRatioFixtures } from './fixtures/tailwind-aspect-ratio-rewrite'
import { caretFixtures } from './fixtures/tailwind-caret-rewrite'
import { backgroundColorFixtures } from './fixtures/tailwind-background-color-rewrite'
import { backgroundStyleFixtures } from './fixtures/tailwind-background-style-rewrite'
import { borderWidthFixtures, roundedFixtures } from './fixtures/tailwind-border-rewrite'
import { displayFixtures } from './fixtures/tailwind-display-rewrite'
import { decorationFixtures } from './fixtures/tailwind-decoration-rewrite'
import { textDecorationFixtures } from './fixtures/tailwind-text-decoration-rewrite'
import { textIndentFixtures } from './fixtures/tailwind-text-indent-rewrite'
import { textShadowFixtures } from './fixtures/tailwind-text-shadow-rewrite'
import { textStrokeFixtures } from './fixtures/tailwind-text-stroke-rewrite'
import { tabSizeFixtures } from './fixtures/tailwind-tab-size-rewrite'
import { textWrapOverflowTransformFixtures } from './fixtures/tailwind-text-wrap-overflow-transform-rewrite'
import { divideFixtures } from './fixtures/tailwind-divide-rewrite'
import { fillFixtures } from './fixtures/tailwind-fill-rewrite'
import { fontFixtures } from './fixtures/tailwind-font-rewrite'
import { fontVariantNumericFixtures } from './fixtures/tailwind-font-variant-numeric-rewrite'
import { leadingFixtures } from './fixtures/tailwind-leading-rewrite'
import { lineClampFixtures } from './fixtures/tailwind-line-clamp-rewrite'
import { outlineFixtures } from './fixtures/tailwind-outline-rewrite'
import { overflowFixtures } from './fixtures/tailwind-overflow-rewrite'
import { positionFloatZOrderBoxSizingFixtures } from './fixtures/tailwind-position-float-z-order-box-sizing-rewrite'
import { ringFixtures } from './fixtures/tailwind-ring-rewrite'
import { shadowFixtures } from './fixtures/tailwind-shadow-rewrite'
import { sizeFixtures } from './fixtures/tailwind-size-rewrite'
import { borderSpacingSpaceFixtures } from './fixtures/tailwind-spacing-border-spacing-space-rewrite'
import { gapInsetScrollFixtures } from './fixtures/tailwind-spacing-gap-inset-scroll-rewrite'
import { paddingMarginFixtures } from './fixtures/tailwind-spacing-padding-margin-rewrite'
import { strokeFixtures } from './fixtures/tailwind-stroke-rewrite'
import { textAlignFixtures } from './fixtures/tailwind-text-align-rewrite'
import { verticalAlignFixtures } from './fixtures/tailwind-vertical-align-rewrite'
import { trackingFixtures } from './fixtures/tailwind-tracking-rewrite'
import { transitionFixtures } from './fixtures/tailwind-transition-rewrite'
import { textFixtures } from './fixtures/tailwind-text-rewrite'
import { tailwindUtilitySpecs } from './tailwind-utility-spec'

function getSpec(id: string) {
  return tailwindUtilitySpecs.find(spec => spec.id === id)
}

describe('tailwind utility spec', () => {
  it('tracks unique utility ids', () => {
    const ids = tailwindUtilitySpecs.map(spec => spec.id)
    expect(new Set(ids).size).toBe(ids.length)
  })

  it('keeps the border rewrite template in sync with the shared fixtures', () => {
    const backgroundColorSpec = getSpec('background-color')
    const displaySpec = getSpec('display')
    const overflowSpec = getSpec('overflow')
    const positionFloatZOrderBoxSizingSpec = getSpec('position-float-z-order-box-sizing')
    const aspectRatioSpec = getSpec('aspect-ratio')
    const sizeSpec = getSpec('size')
    const accentSpec = getSpec('accent')
    const caretSpec = getSpec('caret')
    const backgroundStyleSpec = getSpec('background-style')
    const borderWidthSpec = getSpec('border-width')
    const borderRadiusSpec = getSpec('border-radius')
    const decorationSpec = getSpec('decoration')
    const textDecorationSpec = getSpec('text-decoration')
    const textIndentSpec = getSpec('text-indent')
    const textShadowSpec = getSpec('text-shadow')
    const textStrokeSpec = getSpec('text-stroke')
    const tabSizeSpec = getSpec('tab-size')
    const textWrapOverflowTransformSpec = getSpec('text-wrap-overflow-transform')
    const divideSpec = getSpec('divide')
    const fillSpec = getSpec('fill')
    const fontSpec = getSpec('font')
    const fontVariantNumericSpec = getSpec('font-variant-numeric')
    const lineClampSpec = getSpec('line-clamp')
    const textAlignSpec = getSpec('text-align')
    const verticalAlignSpec = getSpec('vertical-align')
    const borderSpacingSpaceSpec = getSpec('border-spacing-space')
    const leadingSpec = getSpec('leading')
    const gapInsetScrollSpec = getSpec('gap-inset-scroll')
    const outlineSpec = getSpec('outline')
    const paddingMarginSpec = getSpec('padding-margin')
    const ringSpec = getSpec('ring')
    const shadowSpec = getSpec('shadow')
    const strokeSpec = getSpec('stroke')
    const trackingSpec = getSpec('tracking')
    const transitionSpec = getSpec('transition')
    const textSpec = getSpec('text')

    expect(backgroundColorSpec).toBeTruthy()
    expect(displaySpec).toBeTruthy()
    expect(overflowSpec).toBeTruthy()
    expect(positionFloatZOrderBoxSizingSpec).toBeTruthy()
    expect(aspectRatioSpec).toBeTruthy()
    expect(sizeSpec).toBeTruthy()
    expect(accentSpec).toBeTruthy()
    expect(caretSpec).toBeTruthy()
    expect(backgroundStyleSpec).toBeTruthy()
    expect(borderWidthSpec).toBeTruthy()
    expect(borderRadiusSpec).toBeTruthy()
    expect(decorationSpec).toBeTruthy()
    expect(textDecorationSpec).toBeTruthy()
    expect(textIndentSpec).toBeTruthy()
    expect(textShadowSpec).toBeTruthy()
    expect(textStrokeSpec).toBeTruthy()
    expect(tabSizeSpec).toBeTruthy()
    expect(textWrapOverflowTransformSpec).toBeTruthy()
    expect(divideSpec).toBeTruthy()
    expect(fillSpec).toBeTruthy()
    expect(fontSpec).toBeTruthy()
    expect(fontVariantNumericSpec).toBeTruthy()
    expect(lineClampSpec).toBeTruthy()
    expect(textAlignSpec).toBeTruthy()
    expect(verticalAlignSpec).toBeTruthy()
    expect(borderSpacingSpaceSpec).toBeTruthy()
    expect(leadingSpec).toBeTruthy()
    expect(gapInsetScrollSpec).toBeTruthy()
    expect(outlineSpec).toBeTruthy()
    expect(paddingMarginSpec).toBeTruthy()
    expect(ringSpec).toBeTruthy()
    expect(shadowSpec).toBeTruthy()
    expect(strokeSpec).toBeTruthy()
    expect(trackingSpec).toBeTruthy()
    expect(transitionSpec).toBeTruthy()
    expect(textSpec).toBeTruthy()

    expect(displaySpec?.canonical).toEqual([...displayFixtures.canonical])
    expect(displaySpec?.invalid).toEqual([...displayFixtures.invalid])
    expect(displaySpec?.sourceFiles).toEqual(['src/_rules/static.ts'])
    expect(displaySpec?.category).toBe('layout')
    expect(displaySpec?.supportsPrefix).toBe(true)
    expect(displaySpec?.supportsVariants).toBe(true)
    expect(displaySpec?.invalid).toContain('display-block')
    expect(displaySpec?.invalid).toContain('display-[var(--display)]')
    expect(overflowSpec?.canonical).toEqual([...overflowFixtures.canonical])
    expect(overflowSpec?.invalid).toEqual([...overflowFixtures.invalid])
    expect(overflowSpec?.sourceFiles).toEqual(['src/_rules/layout.ts'])
    expect(overflowSpec?.category).toBe('layout')
    expect(overflowSpec?.supportsPrefix).toBe(true)
    expect(overflowSpec?.supportsVariants).toBe(true)
    expect(overflowSpec?.invalid).toContain('overflow-overlay')
    expect(overflowSpec?.invalid).toContain('of-x-auto')
    expect(positionFloatZOrderBoxSizingSpec?.canonical).toEqual([...positionFloatZOrderBoxSizingFixtures.canonical])
    expect(positionFloatZOrderBoxSizingSpec?.invalid).toEqual([...positionFloatZOrderBoxSizingFixtures.invalid])
    expect(positionFloatZOrderBoxSizingSpec?.sourceFiles).toEqual(['src/_rules/position.ts'])
    expect(positionFloatZOrderBoxSizingSpec?.category).toBe('layout')
    expect(positionFloatZOrderBoxSizingSpec?.supportsPrefix).toBe(true)
    expect(positionFloatZOrderBoxSizingSpec?.supportsNegative).toBe(true)
    expect(positionFloatZOrderBoxSizingSpec?.supportsVariants).toBe(true)
    expect(positionFloatZOrderBoxSizingSpec?.invalid).toContain('order2')
    expect(positionFloatZOrderBoxSizingSpec?.invalid).toContain('box-inherit')
    expect(aspectRatioSpec?.canonical).toEqual([...aspectRatioFixtures.canonical])
    expect(aspectRatioSpec?.invalid).toEqual([...aspectRatioFixtures.invalid])
    expect(aspectRatioSpec?.sourceFiles).toEqual(['src/_rules/size.ts'])
    expect(aspectRatioSpec?.category).toBe('layout')
    expect(aspectRatioSpec?.supportsPrefix).toBe(true)
    expect(aspectRatioSpec?.supportsVariants).toBe(true)
    expect(aspectRatioSpec?.invalid).toContain('aspect-ratio-square')
    expect(aspectRatioSpec?.invalid).toContain('size-aspect-square')
    expect(sizeSpec?.canonical).toEqual([...sizeFixtures.canonical])
    expect(sizeSpec?.invalid).toEqual([...sizeFixtures.invalid])
    expect(sizeSpec?.sourceFiles).toEqual(['src/_rules/size.ts'])
    expect(sizeSpec?.category).toBe('layout')
    expect(sizeSpec?.supportsPrefix).toBe(true)
    expect(sizeSpec?.supportsVariants).toBe(true)
    expect(sizeSpec?.canonical).toContain('w-svw')
    expect(sizeSpec?.canonical).toContain('max-w-screen-md')
    expect(sizeSpec?.invalid).toContain('w-xs')
    expect(sizeSpec?.invalid).toContain('size-screen')
    expect(backgroundColorSpec?.canonical).toEqual([...backgroundColorFixtures.canonical])
    expect(backgroundColorSpec?.invalid).toEqual([...backgroundColorFixtures.invalid])
    expect(backgroundColorSpec?.sourceFiles).toEqual(['src/_rules/color.ts'])
    expect(backgroundColorSpec?.category).toBe('color')
    expect(backgroundColorSpec?.supportsPrefix).toBe(true)
    expect(backgroundColorSpec?.supportsVariants).toBe(true)
    expect(backgroundColorSpec?.invalid).toContain('bg-#fff')
    expect(backgroundColorSpec?.invalid).toContain('bg-op50')
    expect(accentSpec?.canonical).toEqual([...accentFixtures.canonical])
    expect(accentSpec?.invalid).toEqual([...accentFixtures.invalid])
    expect(accentSpec?.sourceFiles).toEqual(['src/_rules-wind3/behaviors.ts'])
    expect(accentSpec?.category).toBe('color')
    expect(accentSpec?.supportsPrefix).toBe(true)
    expect(accentSpec?.supportsVariants).toBe(true)
    expect(accentSpec?.invalid).toContain('accent-#fff')
    expect(accentSpec?.invalid).toContain('accent-opacity-50')
    expect(caretSpec?.canonical).toEqual([...caretFixtures.canonical])
    expect(caretSpec?.invalid).toEqual([...caretFixtures.invalid])
    expect(caretSpec?.sourceFiles).toEqual(['src/_rules-wind3/behaviors.ts'])
    expect(caretSpec?.category).toBe('color')
    expect(caretSpec?.supportsPrefix).toBe(true)
    expect(caretSpec?.supportsVariants).toBe(true)
    expect(caretSpec?.invalid).toContain('caret-#fff')
    expect(caretSpec?.invalid).toContain('caret-opacity-50')
    expect(backgroundStyleSpec?.canonical).toEqual([...backgroundStyleFixtures.canonical])
    expect(backgroundStyleSpec?.invalid).toEqual([...backgroundStyleFixtures.invalid])
    expect(backgroundStyleSpec?.sourceFiles).toEqual(['src/_rules-wind3/background.ts'])
    expect(backgroundStyleSpec?.category).toBe('layout')
    expect(backgroundStyleSpec?.supportsPrefix).toBe(true)
    expect(backgroundStyleSpec?.supportsVariants).toBe(true)
    expect(backgroundStyleSpec?.invalid).toContain('bg-gradient-linear')
    expect(backgroundStyleSpec?.invalid).toContain('shape-r')
    expect(decorationSpec?.canonical).toEqual([...decorationFixtures.canonical])
    expect(decorationSpec?.invalid).toEqual([...decorationFixtures.invalid])
    expect(decorationSpec?.sourceFiles).toEqual(['src/_rules/decoration.ts'])
    expect(decorationSpec?.category).toBe('typography')
    expect(decorationSpec?.supportsPrefix).toBe(true)
    expect(decorationSpec?.supportsVariants).toBe(true)
    expect(decorationSpec?.invalid).toContain('decoration-offset-4')
    expect(decorationSpec?.invalid).toContain('underline-dashed')
    expect(textDecorationSpec?.canonical).toEqual([...textDecorationFixtures.canonical])
    expect(textDecorationSpec?.invalid).toEqual([...textDecorationFixtures.invalid])
    expect(textDecorationSpec?.sourceFiles).toEqual(['src/_rules/decoration.ts'])
    expect(textDecorationSpec?.category).toBe('typography')
    expect(textDecorationSpec?.supportsPrefix).toBe(true)
    expect(textDecorationSpec?.supportsVariants).toBe(true)
    expect(textDecorationSpec?.invalid).toContain('decoration-none')
    expect(textDecorationSpec?.invalid).toContain('decoration-line-through')
    expect(textIndentSpec?.canonical).toEqual([...textIndentFixtures.canonical])
    expect(textIndentSpec?.invalid).toEqual([...textIndentFixtures.invalid])
    expect(textIndentSpec?.sourceFiles).toEqual(['src/_rules/typography.ts'])
    expect(textIndentSpec?.category).toBe('typography')
    expect(textIndentSpec?.supportsPrefix).toBe(true)
    expect(textIndentSpec?.supportsNegative).toBe(true)
    expect(textIndentSpec?.supportsVariants).toBe(true)
    expect(textIndentSpec?.invalid).toContain('text-indent-4')
    expect(textIndentSpec?.invalid).toContain('indent-10px')
    expect(textShadowSpec?.canonical).toEqual([...textShadowFixtures.canonical])
    expect(textShadowSpec?.invalid).toEqual([...textShadowFixtures.invalid])
    expect(textShadowSpec?.sourceFiles).toEqual(['src/_rules/typography.ts'])
    expect(textShadowSpec?.category).toBe('typography')
    expect(textShadowSpec?.supportsPrefix).toBe(true)
    expect(textShadowSpec?.supportsVariants).toBe(true)
    expect(textShadowSpec?.canonical).toHaveLength(0)
    expect(textShadowSpec?.invalid).toContain('text-shadow')
    expect(textShadowSpec?.invalid).toContain('text-shadow-color-opacity-50')
    expect(textStrokeSpec?.canonical).toEqual([...textStrokeFixtures.canonical])
    expect(textStrokeSpec?.invalid).toEqual([...textStrokeFixtures.invalid])
    expect(textStrokeSpec?.sourceFiles).toEqual(['src/_rules/typography.ts'])
    expect(textStrokeSpec?.category).toBe('typography')
    expect(textStrokeSpec?.supportsPrefix).toBe(true)
    expect(textStrokeSpec?.supportsVariants).toBe(true)
    expect(textStrokeSpec?.canonical).toHaveLength(0)
    expect(textStrokeSpec?.invalid).toContain('text-stroke')
    expect(textStrokeSpec?.invalid).toContain('text-stroke-opacity-50')
    expect(textWrapOverflowTransformSpec?.canonical).toEqual([...textWrapOverflowTransformFixtures.canonical])
    expect(textWrapOverflowTransformSpec?.invalid).toEqual([...textWrapOverflowTransformFixtures.invalid])
    expect(textWrapOverflowTransformSpec?.sourceFiles).toEqual(['src/_rules/static.ts'])
    expect(textWrapOverflowTransformSpec?.category).toBe('typography')
    expect(textWrapOverflowTransformSpec?.supportsPrefix).toBe(true)
    expect(textWrapOverflowTransformSpec?.supportsVariants).toBe(true)
    expect(textWrapOverflowTransformSpec?.invalid).toContain('text-truncate')
    expect(textWrapOverflowTransformSpec?.invalid).toContain('case-normal')
    expect(tabSizeSpec?.canonical).toEqual([...tabSizeFixtures.canonical])
    expect(tabSizeSpec?.invalid).toEqual([...tabSizeFixtures.invalid])
    expect(tabSizeSpec?.sourceFiles).toEqual(['src/_rules/typography.ts'])
    expect(tabSizeSpec?.category).toBe('typography')
    expect(tabSizeSpec?.supportsPrefix).toBe(true)
    expect(tabSizeSpec?.supportsVariants).toBe(true)
    expect(tabSizeSpec?.canonical).toHaveLength(0)
    expect(tabSizeSpec?.invalid).toContain('tab')
    expect(tabSizeSpec?.invalid).toContain('tab-[var(--n)]')
    expect(divideSpec?.canonical).toEqual([...divideFixtures.canonical])
    expect(divideSpec?.invalid).toEqual([...divideFixtures.invalid])
    expect(divideSpec?.sourceFiles).toEqual(['src/_rules-wind3/divide.ts'])
    expect(divideSpec?.category).toBe('border')
    expect(divideSpec?.supportsPrefix).toBe(true)
    expect(divideSpec?.supportsVariants).toBe(true)
    expect(divideSpec?.invalid).toContain('divide-op50')
    expect(divideSpec?.invalid).toContain('divide-block')
    expect(fillSpec?.canonical).toEqual([...fillFixtures.canonical])
    expect(fillSpec?.invalid).toEqual([...fillFixtures.invalid])
    expect(fillSpec?.sourceFiles).toEqual(['src/_rules/svg.ts'])
    expect(fillSpec?.category).toBe('color')
    expect(fillSpec?.supportsPrefix).toBe(true)
    expect(fillSpec?.supportsVariants).toBe(true)
    expect(fillSpec?.invalid).toContain('fill-#fff')
    expect(fillSpec?.invalid).toContain('fill-opacity-50')
    expect(fontSpec?.canonical).toEqual([...fontFixtures.canonical])
    expect(fontSpec?.invalid).toEqual([...fontFixtures.invalid])
    expect(fontSpec?.sourceFiles).toEqual(['src/_rules/typography.ts'])
    expect(fontSpec?.category).toBe('typography')
    expect(fontSpec?.supportsPrefix).toBe(true)
    expect(fontSpec?.supportsVariants).toBe(true)
    expect(fontSpec?.invalid).toContain('fw-bold')
    expect(fontSpec?.invalid).toContain('font-650')
    expect(fontVariantNumericSpec?.canonical).toEqual([...fontVariantNumericFixtures.canonical])
    expect(fontVariantNumericSpec?.invalid).toEqual([...fontVariantNumericFixtures.invalid])
    expect(fontVariantNumericSpec?.sourceFiles).toEqual(['src/_rules-wind3/typography.ts'])
    expect(fontVariantNumericSpec?.category).toBe('typography')
    expect(fontVariantNumericSpec?.supportsPrefix).toBe(true)
    expect(fontVariantNumericSpec?.supportsVariants).toBe(true)
    expect(fontVariantNumericSpec?.invalid).toContain('nums-normal')
    expect(fontVariantNumericSpec?.invalid).toContain('font-variant-numeric-ordinal')
    expect(lineClampSpec?.canonical).toEqual([...lineClampFixtures.canonical])
    expect(lineClampSpec?.invalid).toEqual([...lineClampFixtures.invalid])
    expect(lineClampSpec?.sourceFiles).toEqual(['src/_rules-wind3/line-clamp.ts'])
    expect(lineClampSpec?.category).toBe('typography')
    expect(lineClampSpec?.supportsPrefix).toBe(true)
    expect(lineClampSpec?.supportsVariants).toBe(true)
    expect(lineClampSpec?.invalid).toContain('line-clamp-0')
    expect(lineClampSpec?.invalid).toContain('line-clamp-revert-layer')
    expect(textAlignSpec?.canonical).toEqual([...textAlignFixtures.canonical])
    expect(textAlignSpec?.invalid).toEqual([...textAlignFixtures.invalid])
    expect(textAlignSpec?.sourceFiles).toEqual(['src/_rules/align.ts'])
    expect(textAlignSpec?.category).toBe('typography')
    expect(textAlignSpec?.supportsPrefix).toBe(true)
    expect(textAlignSpec?.supportsVariants).toBe(true)
    expect(textAlignSpec?.invalid).toContain('text-align-left')
    expect(textAlignSpec?.invalid).toContain('text-align-inherit')
    expect(verticalAlignSpec?.canonical).toEqual([...verticalAlignFixtures.canonical])
    expect(verticalAlignSpec?.invalid).toEqual([...verticalAlignFixtures.invalid])
    expect(verticalAlignSpec?.sourceFiles).toEqual(['src/_rules/align.ts'])
    expect(verticalAlignSpec?.category).toBe('typography')
    expect(verticalAlignSpec?.supportsPrefix).toBe(true)
    expect(verticalAlignSpec?.supportsVariants).toBe(true)
    expect(verticalAlignSpec?.invalid).toContain('vertical-baseline')
    expect(verticalAlignSpec?.invalid).toContain('align-10px')
    expect(ringSpec?.canonical).toEqual([...ringFixtures.canonical])
    expect(ringSpec?.invalid).toEqual([...ringFixtures.invalid])
    expect(ringSpec?.sourceFiles).toEqual(['src/_rules/ring.ts'])
    expect(ringSpec?.category).toBe('behavior')
    expect(ringSpec?.supportsPrefix).toBe(true)
    expect(ringSpec?.supportsVariants).toBe(true)
    expect(ringSpec?.invalid).toContain('ring-op50')
    expect(ringSpec?.invalid).toContain('ring-offset-opacity-50')
    expect(shadowSpec?.canonical).toEqual([...shadowFixtures.canonical])
    expect(shadowSpec?.invalid).toEqual([...shadowFixtures.invalid])
    expect(shadowSpec?.sourceFiles).toEqual(['src/_rules/shadow.ts'])
    expect(shadowSpec?.category).toBe('behavior')
    expect(shadowSpec?.supportsPrefix).toBe(true)
    expect(shadowSpec?.supportsVariants).toBe(true)
    expect(shadowSpec?.invalid).toContain('shadowmd')
    expect(shadowSpec?.invalid).toContain('shadow-inset')
    expect(borderWidthSpec?.invalid).toContain('border-10px')
    expect(borderRadiusSpec?.invalid).toContain('rounded-lt-lg')
    expect(borderWidthSpec?.supportsPrefix).toBe(true)
    expect(borderWidthSpec?.supportsVariants).toBe(true)
    expect(borderRadiusSpec?.supportsPrefix).toBe(true)
    expect(borderRadiusSpec?.supportsVariants).toBe(true)

    expect(borderWidthSpec?.canonical).toEqual([...borderWidthFixtures.canonical])
    expect(borderWidthSpec?.invalid).toEqual([...borderWidthFixtures.invalid])
    expect(borderRadiusSpec?.canonical).toEqual([...roundedFixtures.canonical])
    expect(borderRadiusSpec?.invalid).toEqual([...roundedFixtures.invalid])
    expect(borderSpacingSpaceSpec?.canonical).toEqual([...borderSpacingSpaceFixtures.canonical])
    expect(borderSpacingSpaceSpec?.invalid).toEqual([...borderSpacingSpaceFixtures.invalid])
    expect(borderSpacingSpaceSpec?.sourceFiles).toEqual(['src/_rules-wind3/table.ts', 'src/_rules-wind3/spacing.ts', 'src/rules.ts'])
    expect(borderSpacingSpaceSpec?.category).toBe('layout')
    expect(borderSpacingSpaceSpec?.supportsPrefix).toBe(true)
    expect(borderSpacingSpaceSpec?.supportsVariants).toBe(true)
    expect(borderSpacingSpaceSpec?.invalid).toContain('borderspacing-2')
    expect(borderSpacingSpaceSpec?.invalid).toContain('space-inline-4')
    expect(leadingSpec?.canonical).toEqual([...leadingFixtures.canonical])
    expect(leadingSpec?.invalid).toEqual([...leadingFixtures.invalid])
    expect(leadingSpec?.sourceFiles).toEqual(['src/_rules/typography.ts'])
    expect(leadingSpec?.category).toBe('typography')
    expect(leadingSpec?.supportsPrefix).toBe(true)
    expect(leadingSpec?.supportsVariants).toBe(true)
    expect(leadingSpec?.invalid).toContain('lh-6')
    expect(leadingSpec?.invalid).toContain('leading-20px')
    expect(gapInsetScrollSpec?.canonical).toEqual([...gapInsetScrollFixtures.canonical])
    expect(gapInsetScrollSpec?.invalid).toEqual([...gapInsetScrollFixtures.invalid])
    expect(gapInsetScrollSpec?.sourceFiles).toEqual(['src/_rules/gap.ts', 'src/_rules/position.ts', 'src/_rules-wind3/scrolls.ts'])
    expect(gapInsetScrollSpec?.category).toBe('layout')
    expect(gapInsetScrollSpec?.supportsPrefix).toBe(true)
    expect(gapInsetScrollSpec?.supportsNegative).toBe(true)
    expect(gapInsetScrollSpec?.supportsVariants).toBe(true)
    expect(gapInsetScrollSpec?.invalid).toContain('gap-row-4')
    expect(gapInsetScrollSpec?.invalid).toContain('scroll-m4')
    expect(paddingMarginSpec?.canonical).toEqual([...paddingMarginFixtures.canonical])
    expect(paddingMarginSpec?.invalid).toEqual([...paddingMarginFixtures.invalid])
    expect(paddingMarginSpec?.sourceFiles).toEqual(['src/_rules/spacing.ts'])
    expect(paddingMarginSpec?.category).toBe('layout')
    expect(paddingMarginSpec?.supportsPrefix).toBe(true)
    expect(paddingMarginSpec?.supportsNegative).toBe(true)
    expect(paddingMarginSpec?.supportsVariants).toBe(true)
    expect(paddingMarginSpec?.invalid).toContain('p4')
    expect(paddingMarginSpec?.invalid).toContain('mx-var(--gap)')
    expect(strokeSpec?.canonical).toEqual([...strokeFixtures.canonical])
    expect(strokeSpec?.invalid).toEqual([...strokeFixtures.invalid])
    expect(strokeSpec?.sourceFiles).toEqual(['src/_rules/svg.ts'])
    expect(strokeSpec?.category).toBe('color')
    expect(strokeSpec?.supportsPrefix).toBe(true)
    expect(strokeSpec?.supportsVariants).toBe(true)
    expect(strokeSpec?.invalid).toContain('stroke-width-2')
    expect(strokeSpec?.invalid).toContain('stroke-size-2')
    expect(trackingSpec?.canonical).toEqual([...trackingFixtures.canonical])
    expect(trackingSpec?.invalid).toEqual([...trackingFixtures.invalid])
    expect(trackingSpec?.sourceFiles).toEqual(['src/_rules/typography.ts'])
    expect(trackingSpec?.category).toBe('typography')
    expect(trackingSpec?.supportsPrefix).toBe(true)
    expect(trackingSpec?.supportsVariants).toBe(true)
    expect(trackingSpec?.invalid).toContain('font-tracking-wide')
    expect(trackingSpec?.invalid).toContain('tracking-0.2em')
    expect(transitionSpec?.canonical).toEqual([...transitionFixtures.canonical])
    expect(transitionSpec?.invalid).toEqual([...transitionFixtures.invalid])
    expect(transitionSpec?.sourceFiles).toEqual(['src/_rules/transition.ts', 'src/_theme/transition.ts'])
    expect(transitionSpec?.category).toBe('behavior')
    expect(transitionSpec?.supportsPrefix).toBe(true)
    expect(transitionSpec?.supportsVariants).toBe(true)
    expect(transitionSpec?.invalid).toContain('property-opacity')
    expect(transitionSpec?.invalid).toContain('transition-ease-linear')

    expect(outlineSpec?.canonical).toEqual([...outlineFixtures.canonical])
    expect(outlineSpec?.invalid).toEqual([...outlineFixtures.invalid])
    expect(outlineSpec?.sourceFiles).toEqual(['src/_rules/behaviors.ts'])
    expect(outlineSpec?.category).toBe('behavior')
    expect(outlineSpec?.supportsPrefix).toBe(true)
    expect(outlineSpec?.supportsVariants).toBe(true)
    expect(textSpec?.canonical).toEqual([...textFixtures.canonical])
    expect(textSpec?.invalid).toEqual([...textFixtures.invalid])
    expect(textSpec?.sourceFiles).toEqual(['src/_rules/typography.ts'])
    expect(textSpec?.category).toBe('typography')
    expect(textSpec?.supportsPrefix).toBe(true)
    expect(textSpec?.supportsVariants).toBe(true)
    expect(textSpec?.invalid).toContain('text-#fff')
    expect(textSpec?.invalid).toContain('text-color-red-500')

    for (const spec of [backgroundColorSpec, accentSpec, caretSpec, backgroundStyleSpec, borderWidthSpec, borderRadiusSpec, decorationSpec, textDecorationSpec, textIndentSpec, textWrapOverflowTransformSpec, tabSizeSpec, divideSpec, fillSpec, fontSpec, textAlignSpec, verticalAlignSpec, borderSpacingSpaceSpec, leadingSpec, gapInsetScrollSpec, outlineSpec, paddingMarginSpec, ringSpec, shadowSpec, strokeSpec, trackingSpec, transitionSpec, textSpec].filter(Boolean)) {
      if (spec?.id !== 'tab-size')
        expect(spec?.canonical.length).toBeGreaterThan(0)
      expect(spec?.invalid.length).toBeGreaterThan(0)
      expect(spec?.sourceFiles.length).toBeGreaterThan(0)
    }
  })
})
