import type { Theme } from './types'
import { colors } from './colors'
import { blur, brightness, contrast, dropShadow, grayscale, hueRotate, invert, opacity, saturate, sepia } from './filters'
import { fontFamily, fontSize, fontWeight, letterSpacing, lineHeight, textIndent, textShadow, textStrokeWidth, wordSpacing } from './font'
import { borderRadius, boxShadow, breakpoints, duration, flexGrow, flexShrink, lineWidth, media, order, ringWidth, rotate, scale, skew, spacing, transformOrigin, translate, verticalBreakpoints, willChange, zIndex } from './misc'
import { preflightBase } from './preflight'
import { aspectRatio, blockSize, columns, containers, flexBasis, gridAutoColumns, gridAutoRows, gridColumn, gridColumnEnd, gridColumnStart, gridRow, gridRowEnd, gridRowStart, gridTemplateColumns, gridTemplateRows, height, inlineSize, maxBlockSize, maxHeight, maxInlineSize, maxWidth, minHeight, minWidth, width } from './size'
import { easing, transitionProperty } from './transition'

export const theme = {
  aspectRatio,
  width,
  height,
  maxWidth,
  maxHeight,
  minWidth,
  minHeight,
  inlineSize,
  blockSize,
  maxInlineSize,
  maxBlockSize,
  minInlineSize: maxInlineSize,
  minBlockSize: maxBlockSize,
  colors,
  fontFamily,
  fontSize,
  fontWeight,
  breakpoints,
  verticalBreakpoints,
  borderRadius,
  lineHeight,
  letterSpacing,
  wordSpacing,
  boxShadow,
  textIndent,
  textShadow,
  textStrokeWidth,
  blur,
  brightness,
  contrast,
  dropShadow,
  grayscale,
  hueRotate,
  invert,
  opacity,
  rotate,
  saturate,
  scale,
  sepia,
  skew,
  transformOrigin,
  easing,
  transitionProperty,
  willChange,
  lineWidth,
  spacing,
  translate,
  duration,
  ringWidth,
  order,
  preflightBase,
  columns,
  containers,
  flexBasis,
  flexGrow,
  flexShrink,
  gridAutoColumns,
  gridAutoRows,
  gridColumn,
  gridColumnEnd,
  gridColumnStart,
  gridRow,
  gridRowEnd,
  gridRowStart,
  gridTemplateColumns,
  gridTemplateRows,
  zIndex,
  media,
} satisfies Theme
