import type { BlocklistRule } from '@unocss/core'

const rawLengthUnit = String.raw`(?:%|px|r?em|ex|ch|vh|vw|vmin|vmax|svh|svw|lvh|lvw|dvh|dvw|cm|mm|in|pt|pc)`
const rawLengthValue = String.raw`(?:\d+\.?\d*|\d*\.\d+)${rawLengthUnit}`
const rawCssFunctionValue = String.raw`(?:var|calc|min|max|clamp)\(.+\)`
const rawArbitraryValue = String.raw`(?:${rawLengthValue}|${rawCssFunctionValue})`

export const blocklist: BlocklistRule[] = [
  /^(?:w|h)\d\S*$/,
  /^(?:min|max)[wh]\S*$/,
  /^size-[wh]-\S+$/,
  /^-?(?:m|p)[trblxy]?\d\S*$/,
  /^-?(?:m|p)-[trblxy]-\S+$/,
  /^b-.+$/,
  /^rd-.+$/,
  /^gap\d\S*$/,
  /^gap[xy]\d\S*$/,
  /^gap[xy]-\S+$/,
  /^divide[xy]\S*$/,
  /^scroll[mp]\S*$/,
  /^keyframes-\S+$/,
  /^animate-name-\S+$/,
  /^animate-(?:duration|delay|ease)-\S+$/,
  /^animate-(?:fill(?:-mode)?|mode)-\S+$/,
  /^animate-direction-\S+$/,
  /^animate-(?:iteration-count|iteration|count)-\S+$/,
  /^animate-(?:play-state|play|state)-\S+$/,
  /^bg-gradient-(?:repeating-)?(?:linear|radial|conic)$/,
  /^bg-gradient-(?:from|via)-.+$/,
  /^bg-gradient-to-(?![rltb]{1,2}$).+$/,
  /^bg-gradient-shape-.+$/,
  /^bg-gradient-stops-.+$/,
  /^shape-.+$/,
  /^font(?!-|\[)\S+$/,
  /^fw-.+$/,
  /^of-.+$/,
  /^pos-.+$/,
  /^z\d\S*$/,
  /^flex-inline$/,
  /^flex-basis-.+$/,
  /^flex-grow-(?!0$).+$/,
  /^flex-shrink-(?!0$).+$/,
  /^auto-flow-.+$/,
  /^(?:cols|rows)-.+$/,
  /^op\d\S*$/,
  /^filter-(?:blur|brightness|contrast|drop-shadow|grayscale|hue-rotate|invert|saturate|sepia)(?:-.+)?$/,
  /^drop-shadow-color(?:-.+)?$/,
  /^transform-rotate-.+$/,
  /^transform-origin-.+$/,
  /^perspective(?:-origin)?-.+$/,
  /^preserve-(?:3d|flat)$/,
  new RegExp(`^(?:size|(?:min|max)-[wh]|[wh])-${rawArbitraryValue}$`),
  new RegExp(`^-?(?:m|p)(?:[trblxy]|[se]|[bi][se]|block|inline)?-${rawArbitraryValue}$`),
  new RegExp(`^(?:flex-|grid-)?gap(?:-[xy]|-(?:col|row))?-${rawArbitraryValue}$`),
  new RegExp(`^-?(?:inset(?:-[xy]|-(?:block|inline)|-[rltbse]|-[bi][se])?|(?:top|right|bottom|left|start|end))-${rawArbitraryValue}$`),
  new RegExp(`^-?translate-(?:[xyz]-)?${rawArbitraryValue}$`),
  new RegExp(`^scroll-[mp](?:[trblxy]|[se]|[bi][se])?-${rawArbitraryValue}$`),
]
